// Generated by build-breakeven.js from the IPCEI Clean Hydrogen Observatory
// break-even price datasets (https://ipcei.observatory.clean-hydrogen.europa.eu/tools-reports/datasets). Do not hand-edit.
window.BREAKEVEN_META = {
  "label": "IPCEI Clean Hydrogen Observatory — Break-Even Prices of Renewable Hydrogen (2022-2025)",
  "source": "https://ipcei.observatory.clean-hydrogen.europa.eu/tools-reports/datasets",
  "years": [
    2022,
    2023,
    2024,
    2025
  ]
};
window.BREAKEVEN_DATA = {
  "years": [
    2022,
    2023,
    2024,
    2025
  ],
  "sectors": {
    "refining": {
      "label": "Oil Refining",
      "unit": "EUR/kg",
      "series": [
        {
          "key": "Austria",
          "values": [
            5.979,
            3.669,
            2.953,
            3.316
          ]
        },
        {
          "key": "Belgium",
          "values": [
            4.498,
            2.975,
            2.394,
            2.628
          ]
        },
        {
          "key": "Bulgaria",
          "values": [
            5.752,
            3.324,
            2.587,
            2.646
          ]
        },
        {
          "key": "Croatia",
          "values": [
            3.979,
            3.332,
            3.383,
            3.218
          ]
        },
        {
          "key": "Czechia",
          "values": [
            4.611,
            3.608,
            3.098,
            3.299
          ]
        },
        {
          "key": "Denmark",
          "values": [
            6.372,
            3.393,
            2.969,
            3.265
          ]
        },
        {
          "key": "Estonia",
          "values": [
            5.862,
            4.269,
            3.289,
            3.303
          ]
        },
        {
          "key": "Finland",
          "values": [
            6.789,
            4.403,
            3.531,
            3.775
          ]
        },
        {
          "key": "France",
          "values": [
            4.17,
            3.389,
            2.503,
            2.608
          ]
        },
        {
          "key": "Germany",
          "values": [
            5.339,
            3.393,
            2.947,
            3.265
          ]
        },
        {
          "key": "Greece",
          "values": [
            6.117,
            3.486,
            2.746,
            2.675
          ]
        },
        {
          "key": "Hungary",
          "values": [
            5.963,
            3.766,
            3.09,
            3.195
          ]
        },
        {
          "key": "Ireland",
          "values": [
            4.643,
            3.194,
            2.4,
            3.364
          ]
        },
        {
          "key": "Italy",
          "values": [
            6.226,
            3.559,
            2.816,
            2.963
          ]
        },
        {
          "key": "Latvia",
          "values": [
            4.967,
            4.415,
            3.097,
            3.046
          ]
        },
        {
          "key": "Lithuania",
          "values": [
            6.105,
            3.993,
            2.265,
            2.211
          ]
        },
        {
          "key": "Luxembourg",
          "values": [
            5.129,
            5.571,
            4.037,
            2.874
          ]
        },
        {
          "key": "Netherlands",
          "values": [
            5.036,
            3.105,
            2.524,
            3.094
          ]
        },
        {
          "key": "Poland",
          "values": [
            4.182,
            3.409,
            3.185,
            3.114
          ]
        },
        {
          "key": "Portugal",
          "values": [
            5.21,
            3.49,
            2.588,
            2.714
          ]
        },
        {
          "key": "Romania",
          "values": [
            6.404,
            3.089,
            2.644,
            2.924
          ]
        },
        {
          "key": "Slovakia",
          "values": [
            4.481,
            4.533,
            3.603,
            4.2
          ]
        },
        {
          "key": "Slovenia",
          "values": [
            3.943,
            3.616,
            3.144,
            3.113
          ]
        },
        {
          "key": "Spain",
          "values": [
            4.696,
            2.74,
            2.37,
            2.441
          ]
        },
        {
          "key": "Sweden",
          "values": [
            8.137,
            4.93,
            4.536,
            4.586
          ]
        }
      ]
    },
    "hdtrucks": {
      "label": "Heavy-Duty Trucks",
      "unit": "EUR/kg",
      "series": [
        {
          "key": "Austria",
          "values": [
            9.355,
            3.85,
            3.361,
            4.883
          ]
        },
        {
          "key": "Belgium",
          "values": [
            9.837,
            4.19,
            3.449,
            5.629
          ]
        },
        {
          "key": "Bulgaria",
          "values": [
            8.102,
            3.35,
            2.277,
            4.154
          ]
        },
        {
          "key": "Croatia",
          "values": [
            9.314,
            3.45,
            3.088,
            4.182
          ]
        },
        {
          "key": "Cyprus",
          "values": [
            9.215,
            3.72,
            2.842,
            4.562
          ]
        },
        {
          "key": "Czechia",
          "values": [
            8.802,
            3.46,
            2.857,
            4
          ]
        },
        {
          "key": "Denmark",
          "values": [
            9.706,
            4.02,
            4.732,
            5.709
          ]
        },
        {
          "key": "Estonia",
          "values": [
            9.053,
            3.5,
            3.458,
            4.242
          ]
        },
        {
          "key": "Finland",
          "values": [
            10.428,
            4.35,
            4.178,
            6.528
          ]
        },
        {
          "key": "France",
          "values": [
            9.766,
            4.22,
            4.154,
            5.68
          ]
        },
        {
          "key": "Germany",
          "values": [
            9.686,
            4.21,
            4.414,
            5.235
          ]
        },
        {
          "key": "Greece",
          "values": [
            9.578,
            3.81,
            4.046,
            4.338
          ]
        },
        {
          "key": "Hungary",
          "values": [
            9.132,
            3.37,
            2.944,
            3.976
          ]
        },
        {
          "key": "Ireland",
          "values": [
            9.794,
            4.16,
            3.938,
            4.809
          ]
        },
        {
          "key": "Italy",
          "values": [
            9.971,
            4.18,
            4.006,
            5.068
          ]
        },
        {
          "key": "Latvia",
          "values": [
            9.283,
            3.82,
            3.495,
            4.776
          ]
        },
        {
          "key": "Lithuania",
          "values": [
            8.627,
            3.22,
            2.982,
            4.898
          ]
        },
        {
          "key": "Luxembourg",
          "values": [
            8.832,
            3.6,
            3.387,
            4.814
          ]
        },
        {
          "key": "Malta",
          "values": [
            7.1,
            2.4,
            2.664,
            2.206
          ]
        },
        {
          "key": "Netherlands",
          "values": [
            9.932,
            4.17,
            4.753,
            6.114
          ]
        },
        {
          "key": "Poland",
          "values": [
            7.748,
            3.52,
            2.721,
            3.576
          ]
        },
        {
          "key": "Portugal",
          "values": [
            9.195,
            3.59,
            3.896,
            4.898
          ]
        },
        {
          "key": "Romania",
          "values": [
            8.446,
            3.33,
            3.059,
            4.625
          ]
        },
        {
          "key": "Slovakia",
          "values": [
            8.986,
            3.53,
            3.423,
            4.198
          ]
        },
        {
          "key": "Slovenia",
          "values": [
            9.067,
            3.39,
            3.117,
            4.214
          ]
        },
        {
          "key": "Spain",
          "values": [
            8.969,
            3.41,
            3.21,
            4.031
          ]
        },
        {
          "key": "Sweden",
          "values": [
            11.06,
            3.79,
            3.147,
            5.014
          ]
        }
      ],
      "seriesAtProduction": [
        {
          "key": "Austria",
          "values": [
            5.629,
            0.59,
            0.101,
            1.623
          ]
        },
        {
          "key": "Belgium",
          "values": [
            6.111,
            0.93,
            0.189,
            2.369
          ]
        },
        {
          "key": "Bulgaria",
          "values": [
            4.376,
            0.09,
            -0.983,
            0.894
          ]
        },
        {
          "key": "Croatia",
          "values": [
            5.588,
            0.19,
            -0.172,
            0.922
          ]
        },
        {
          "key": "Cyprus",
          "values": [
            5.489,
            0.46,
            -0.418,
            1.302
          ]
        },
        {
          "key": "Czechia",
          "values": [
            5.076,
            0.2,
            -0.403,
            0.74
          ]
        },
        {
          "key": "Denmark",
          "values": [
            5.98,
            0.76,
            1.472,
            2.449
          ]
        },
        {
          "key": "Estonia",
          "values": [
            5.327,
            0.24,
            0.198,
            0.982
          ]
        },
        {
          "key": "Finland",
          "values": [
            6.702,
            1.09,
            0.918,
            3.268
          ]
        },
        {
          "key": "France",
          "values": [
            6.04,
            0.96,
            0.894,
            2.42
          ]
        },
        {
          "key": "Germany",
          "values": [
            5.96,
            0.95,
            1.154,
            1.975
          ]
        },
        {
          "key": "Greece",
          "values": [
            5.852,
            0.55,
            0.786,
            1.078
          ]
        },
        {
          "key": "Hungary",
          "values": [
            5.406,
            0.11,
            -0.316,
            0.716
          ]
        },
        {
          "key": "Ireland",
          "values": [
            6.068,
            0.9,
            0.678,
            1.549
          ]
        },
        {
          "key": "Italy",
          "values": [
            6.245,
            0.92,
            0.746,
            1.808
          ]
        },
        {
          "key": "Latvia",
          "values": [
            5.557,
            0.56,
            0.235,
            1.516
          ]
        },
        {
          "key": "Lithuania",
          "values": [
            4.901,
            -0.04,
            -0.278,
            1.638
          ]
        },
        {
          "key": "Luxembourg",
          "values": [
            5.106,
            0.33,
            0.127,
            1.554
          ]
        },
        {
          "key": "Malta",
          "values": [
            3.374,
            -0.87,
            -0.596,
            -1.054
          ]
        },
        {
          "key": "Netherlands",
          "values": [
            6.206,
            0.91,
            1.493,
            2.854
          ]
        },
        {
          "key": "Poland",
          "values": [
            4.022,
            0.26,
            -0.539,
            0.316
          ]
        },
        {
          "key": "Portugal",
          "values": [
            5.469,
            0.33,
            0.636,
            1.638
          ]
        },
        {
          "key": "Romania",
          "values": [
            4.72,
            0.07,
            -0.201,
            1.365
          ]
        },
        {
          "key": "Slovakia",
          "values": [
            5.26,
            0.27,
            0.163,
            0.938
          ]
        },
        {
          "key": "Slovenia",
          "values": [
            5.341,
            0.13,
            -0.143,
            0.954
          ]
        },
        {
          "key": "Spain",
          "values": [
            5.243,
            0.15,
            -0.05,
            0.771
          ]
        },
        {
          "key": "Sweden",
          "values": [
            7.334,
            0.53,
            -0.113,
            1.754
          ]
        }
      ]
    },
    "maritime": {
      "label": "Maritime",
      "unit": "EUR/kg",
      "series": [
        {
          "key": "Cruise ship (100,000 - 150,000 GT)",
          "values": [
            1.901,
            2.339,
            1.858,
            2.18
          ]
        },
        {
          "key": "Feeder containership (1,000 - 1,999 TEU)",
          "values": [
            2.067,
            2.522,
            2.033,
            2.381
          ]
        },
        {
          "key": "Large intercontinental containership (12,000 - 20,000 TEU)",
          "values": [
            1.162,
            1.516,
            1.076,
            1.394
          ]
        },
        {
          "key": "Ro-Pax ferry (20,000+ GT)",
          "values": [
            2.206,
            2.681,
            2.182,
            2.538
          ]
        }
      ]
    }
  }
};
