// H₂Grid v6 — IEA "announced projects" tier.
// Renders the full IEA Hydrogen Production & Infrastructure databases
// (window.IEA_DATA, generated by build-iea.py) as a clustered holo layer
// beneath the curated network. Location-approximate records are flagged.

(function () {
  const IEA = window.IEA_DATA;
  const META = window.IEA_META || { count: 0 };
  if (!IEA) return;

  const HOLO = "#3fd6e8";

  // Register with the dock toggle system (app.js wires buttons on load).
  TOGGLE_MAP.announced = ["iea-clusters", "iea-cluster-count", "iea-points"];

  // 936 of the 3,338 IEA records arrive with no coordinates at all. build-iea.js
  // falls back to the country centroid plus a deterministic jitter so the record
  // is not lost — but a centroid is not a location: Australia's land in the
  // Simpson Desert, America's in rural Kansas, Japan's in the Japanese Alps.
  // Plotting them alongside surveyed coordinates makes the map assert positions
  // the source never claimed, so they are excluded unless explicitly requested.
  function showApprox() {
    return Boolean(document.getElementById("data-quality-approx")?.checked);
  }

  function filteredIEA() {
    const approxOn = showApprox();
    const cohort = window.H2Store?.getState().filters.cohort;
    const cohortProperty = cohort?.type === "endUse" ? {
      Refining: "end_refining", Ammonia: "end_ammonia", Methanol: "end_methanol",
      "Iron & Steel": "end_iron_steel", Mobility: "end_mobility", Power: "end_power",
      "Grid & Blending": "end_grid_inj", "Bio / Synfuels": "end_synfuels"
    }[cohort.value] : null;
    return {
      type: "FeatureCollection",
      features: IEA.features.filter((f) => {
        const p = f.properties;
        if (!approxOn && Number(p.approx)) return false;
        if (statusFilter !== "all" && p.statusClass !== statusFilter) return false;
        if (regionFilter !== "all" && !(REGION_GROUPS[regionFilter] || []).includes(p.region)) return false;
        if (colorFilter && p.color !== colorFilter) return false;
        if (cohortProperty && !Number(p[cohortProperty]) && !(cohort.value === "Grid & Blending" && (Number(p.end_chp) || Number(p.end_domestic_heat))) && !(cohort.value === "Bio / Synfuels" && Number(p.end_biofuels))) return false;
        return true;
      })
    };
  }

  map.on("load", () => {
    const beforeId = map.getLayer("hubs") ? "hubs" : undefined;

    map.addSource("iea", {
      type: "geojson", data: filteredIEA(),
      cluster: true, clusterRadius: 42, clusterMaxZoom: 8
    });

    map.addLayer({
      id: "iea-clusters", type: "circle", source: "iea",
      filter: ["has", "point_count"],
      paint: {
        // Near-empty glass disc: the ring defines the cluster, the faint fill
        // just separates it from the basemap. Ring opacity scales with how many
        // projects the cluster holds, so a 400-project cluster reads heavier
        // than a 3-project one without changing colour or adding a second layer.
        "circle-color": "rgba(63, 214, 232, 0.05)",
        "circle-stroke-color": HOLO,
        "circle-stroke-width": 1.1,
        "circle-stroke-opacity": ["interpolate", ["linear"], ["get", "point_count"],
          2, 0.34, 400, 0.72],
        "circle-blur": 0.06,
        "circle-radius": ["step", ["get", "point_count"], 12, 25, 17, 100, 23, 400, 30]
      }
    }, beforeId);

    map.addLayer({
      id: "iea-cluster-count", type: "symbol", source: "iea",
      filter: ["has", "point_count"],
      layout: {
        "text-field": ["get", "point_count_abbreviated"],
        "text-font": ["Noto Sans Regular"],
        "text-size": 10
      },
      paint: { "text-color": HOLO, "text-halo-color": "#01030a", "text-halo-width": 1 }
    }, beforeId);

    map.addLayer({
      id: "iea-points", type: "circle", source: "iea",
      filter: ["!", ["has", "point_count"]],
      paint: {
        "circle-color": HOLO,
        // Softened to match the curated markers: no hard edge, lower opacity.
        "circle-radius": ["+", 2.6, ["*", 0.6, ["coalesce", ["get", "scale"], 1]]],
        "circle-blur": 0.65,
        // Country-centroid records, when switched on, are drawn as a hollow ring
        // instead of a filled cloud. A viewer must be able to tell at a glance
        // which dots are a surveyed position and which are only "somewhere in
        // this country" — same encoding the detail panel already spells out.
        "circle-opacity": ["*",
          ["match", ["get", "statusClass"], "operating", 0.55, "construction", 0.46, "atrisk", 0.3, 0.28],
          ["case", ["==", ["to-number", ["coalesce", ["get", "approx"], 0]], 1], 0.12, 1]
        ],
        "circle-stroke-color": HOLO,
        "circle-stroke-opacity": 0.45,
        "circle-stroke-width": ["case", ["==", ["to-number", ["coalesce", ["get", "approx"], 0]], 1], 1, 0]
      }
    }, beforeId);

    // Interactions
    map.on("click", "iea-clusters", (e) => {
      const f = e.features[0];
      const src = map.getSource("iea");
      if (src.getClusterExpansionZoom) {
        src.getClusterExpansionZoom(f.properties.cluster_id, (err, zoom) => {
          if (err) return;
          if (typeof stopSpin === "function") stopSpin();
          map.easeTo({ center: f.geometry.coordinates, zoom: zoom + 0.4, duration: 900 });
        });
      }
    });
    map.on("click", "iea-points", (e) => {
      const p = Object.assign({}, e.features[0].properties);
      p.operator = p.country;
      p.source = META.source;
      p.note = "IEA database record (" + META.label + "). Location " +
        (Number(p.approx) ? "approximate — plotted at country level." : "as reported by the IEA.");
      selectFacility(p, [e.lngLat.lng, e.lngLat.lat]);
    });
    ["iea-clusters", "iea-points"].forEach((id) => {
      map.on("mouseenter", id, (e) => {
        map.getCanvas().style.cursor = "pointer";
        const p = e.features[0].properties;
        if (p.point_count) return;
        hoverPopup.setLngLat(e.lngLat)
          .setHTML(`<div class="popup-title">${escapeHtml(p.name)}</div><div class="popup-sub">IEA · ${escapeHtml(p.subtype || "")} · ${escapeHtml(p.status || "")}</div>`)
          .addTo(map);
      });
      map.on("mouseleave", id, () => {
        map.getCanvas().style.cursor = "";
        hoverPopup.remove();
      });
    });

    // Announced-tier counter
    const el = document.getElementById("stat-iea");
    if (el && typeof countUp === "function") countUp("stat-iea", META.count);
  });

  // Chain into the curated filter pipeline: rebuilding the clustered source
  // recomputes clusters under the active filters.
  const _applyFilters = applyFilters;
  applyFilters = function () {
    _applyFilters();
    if (map.getSource && map.getSource("iea")) map.getSource("iea").setData(filteredIEA());
  };

  // The approximate-position control needs no TOGGLE_MAP entry — it changes
  // which features the source contains, not a layer's visibility. Deferred to a
  // macrotask because wireDock() in 03-filters.js is what flips .active, and it
  // binds later than this module parses; running synchronously here would read
  // the class from before the toggle and invert the switch.
  document.getElementById("data-quality-approx")?.addEventListener("change", () => {
    if (typeof applyFilters === "function") applyFilters();
  });

  // Exposed for verification.
  window.H2GIea = {
    debug() {
      return {
        total: IEA.features.length,
        countryCentroidRecords: IEA.features.filter((f) => Number(f.properties.approx)).length,
        approxShown: showApprox(),
        plotted: filteredIEA().features.length
      };
    }
  };
})();
