#!/usr/bin/env python3
"""H2Grid — hydrogen news refresh.
Pulls public RSS feeds from IEA, Bloomberg Green, NYT Climate, S&P Global,
Reuters Energy, Hydrogen Insight, and Recharge News; filters to
hydrogen-relevant entries; asks Claude for a one-line HUD-voice summary of
each; writes js/news-data.js. Rerun manually whenever you want fresh
headlines — nothing here runs on a schedule.

Usage:
  ANTHROPIC_API_KEY=sk-... python3 build-news.py
  python3 build-news.py --selftest      # offline check, no network/API calls
"""
import json, os, re, sys, urllib.request
import xml.etree.ElementTree as ET

FEEDS = [
    ("IEA", "https://www.iea.org/news/rss"),
    ("Bloomberg Green", "https://feeds.bloomberg.com/green/news.rss"),
    ("NYT Climate", "https://rss.nytimes.com/services/xml/rss/nyt/Climate.xml"),
    ("S&P Global", "https://www.spglobal.com/commodityinsights/en/rss-feed/energy-transition"),
    ("Reuters Energy", "https://www.reutersagency.com/feed/?best-sectors=energy"),
    ("Hydrogen Insight", "https://www.hydrogeninsight.com/rss"),
    ("Recharge News", "https://www.rechargenews.com/rss"),
]

KEYWORDS = re.compile(r"hydrogen|electroly[sz]er|fuel cell|\bh2\b|green steel", re.I)

MAX_CANDIDATES = 10
MAX_OUTPUT = 8

OUT_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), "js", "news-data.js")


def fetch_feed(url, timeout=15):
    req = urllib.request.Request(url, headers={"User-Agent": "H2Grid/1.0"})
    with urllib.request.urlopen(req, timeout=timeout) as resp:
        return resp.read()


def parse_rss(xml_bytes):
    """Return [{title, link, summary, date}] from an RSS 2.0 payload."""
    root = ET.fromstring(xml_bytes)
    items = []
    for item in root.iter("item"):
        title = (item.findtext("title") or "").strip()
        link = (item.findtext("link") or "").strip()
        summary = (item.findtext("description") or "").strip()
        summary = re.sub(r"<[^>]+>", "", summary)  # strip any embedded HTML
        date = (item.findtext("pubDate") or "").strip()
        if title and link:
            items.append({"title": title, "link": link, "summary": summary, "date": date})
    return items


def relevant(entry):
    return bool(KEYWORDS.search(entry["title"] + " " + entry["summary"]))


def collect_candidates():
    candidates = []
    for source, url in FEEDS:
        try:
            entries = parse_rss(fetch_feed(url))
        except Exception as err:
            print(f"skip {source}: {err}", file=sys.stderr)
            continue
        for e in entries:
            if relevant(e):
                candidates.append({**e, "source": source})
    return candidates[:MAX_CANDIDATES]


def summarize(entry, api_key):
    """One-line HUD-voice summary via the Claude API. Falls back to the
    feed's own snippet (truncated) if no API key is configured."""
    if not api_key:
        snippet = entry["summary"] or entry["title"]
        return snippet[:140]
    body = json.dumps({
        "model": "claude-sonnet-5",
        "max_tokens": 60,
        "messages": [{
            "role": "user",
            "content": (
                "Write ONE punchy sentence (max 140 characters, no quotes, no "
                "hashtags) summarizing this hydrogen-industry article for a "
                "mission-control HUD readout:\n\n"
                f"Title: {entry['title']}\nSnippet: {entry['summary']}"
            )
        }]
    }).encode("utf-8")
    req = urllib.request.Request(
        "https://api.anthropic.com/v1/messages",
        data=body,
        headers={
            "content-type": "application/json",
            "x-api-key": api_key,
            "anthropic-version": "2023-06-01"
        }
    )
    with urllib.request.urlopen(req, timeout=30) as resp:
        data = json.load(resp)
    return data["content"][0]["text"].strip()[:140]


def build_records(candidates, api_key):
    out = []
    for entry in candidates[:MAX_OUTPUT]:
        out.append({
            "source": entry["source"],
            "headline": entry["title"],
            "summary": summarize(entry, api_key),
            "url": entry["link"],
            "date": entry["date"]
        })
    return out


def write_js(records):
    with open(OUT_PATH, "w", encoding="utf-8") as f:
        f.write("// Generated by build-news.py — do not hand-edit. Rerun the script for fresh headlines.\n")
        f.write("window.HYDROGEN_NEWS = ")
        json.dump(records, f, indent=2, ensure_ascii=False)
        f.write(";\n")


def selftest():
    """Offline check: RSS parsing + keyword filter + summary fallback, no network."""
    sample_xml = b"""<?xml version="1.0"?>
    <rss><channel>
      <item><title>Green hydrogen plant opens in Texas</title>
        <link>https://example.com/a</link>
        <description>A new &lt;b&gt;electrolyzer&lt;/b&gt; facility begins operating.</description>
        <pubDate>Mon, 01 Jul 2026 00:00:00 GMT</pubDate></item>
      <item><title>Local bakery wins award</title>
        <link>https://example.com/b</link>
        <description>Unrelated to energy.</description>
        <pubDate>Mon, 01 Jul 2026 00:00:00 GMT</pubDate></item>
    </channel></rss>"""
    entries = parse_rss(sample_xml)
    assert len(entries) == 2, f"expected 2 items, got {len(entries)}"
    assert entries[0]["summary"] == "A new electrolyzer facility begins operating.", entries[0]["summary"]
    rel = [e for e in entries if relevant(e)]
    assert len(rel) == 1 and rel[0]["title"].startswith("Green hydrogen"), "keyword filter should keep only the hydrogen item"
    summary = summarize({**rel[0], "source": "Test"}, api_key="")
    assert summary == "A new electrolyzer facility begins operating.", "no-key fallback should reuse the snippet"
    print("PASS  selftest: RSS parse, keyword filter, no-key summary fallback")


def main():
    if "--selftest" in sys.argv:
        selftest()
        return
    api_key = os.environ.get("ANTHROPIC_API_KEY", "")
    if not api_key:
        print("ANTHROPIC_API_KEY not set — using feed snippets instead of LLM summaries.", file=sys.stderr)
    candidates = collect_candidates()
    if not candidates:
        print("No hydrogen-relevant entries found across feeds — leaving news-data.js untouched.", file=sys.stderr)
        return
    records = build_records(candidates, api_key)
    write_js(records)
    print(f"Wrote {len(records)} headlines to {OUT_PATH}")


if __name__ == "__main__":
    main()
